// Code generated by "stringer -type=FeedUpdateAction"; DO NOT EDIT.

package messaging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FeedsUpdateOne-0]
	_ = x[FeedsUpdateAll-1]
}

const _FeedUpdateAction_name = "FeedsUpdateOneFeedsUpdateAll"

var _FeedUpdateAction_index = [...]uint8{0, 14, 28}

func (i MessageType) String() string {
	if i >= MessageType(len(_FeedUpdateAction_index)-1) {
		return "FeedUpdateAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FeedUpdateAction_name[_FeedUpdateAction_index[i]:_FeedUpdateAction_index[i+1]]
}
