// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package processor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FeedsUpdateOne-0]
	_ = x[FeedsUpdateAll-1]
}

const _MessageType_name = "FeedsUpdateOneFeedsUpdateAll"

var _MessageType_index = [...]uint8{0, 14, 28}

func (i MessageType) String() string {
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
